### ISSUE TITLE
Embed Message

### ISSUE THREAD

**Issue by SirEduRs** [preilakos/mtasa-dcwebhook#1]
How could I make an embed message? To make the base of the embed it would be in "content = message" ?

**Comment by preilakos** [comment]
Hi. I didn't tried it yet, but i think using [this website](https://discohook.org/) will help you. After you customized it on the website, you can try to add new arrays to the script.

**Comment by SirEduRs** [comment]
Where I could insert the json code, because I tried to insert in the formFields it didn't work, I tried in the function of the command I'm creating but it wasn't
